framework:
  notifier:
    texter_transports:
      twilio: "twilio://%env(TWILIO_ACCOUNT_SID)%:%env(TWILIO_AUTH_TOKEN)%@default?from=%env(TWILIO_FROM)%"
    channel_policy:
      urgent: ["sms"]
      high: ["sms"]
      medium: ["sms"]
      low: ["sms"]
    # Désactiver Messenger pour les SMS
    message_bus: null
