<?php

namespace ContainerWPo7wjW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AgMh5_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._AgMh5.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._AgMh5.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
        ], [
            'paginator' => '?',
            'repository' => 'App\\Repository\\ServicesRepository',
        ]);
    }
}
