<?php

namespace ContainerEO8BScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0HTT1JAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0HTT1JA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0HTT1JA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RendezVousController::AfficheRendezVous' => ['privates', '.service_locator.kMnENF0', 'get_ServiceLocator_KMnENF0Service', true],
            'App\\Controller\\RendezVousController::Delete' => ['privates', '.service_locator.NoFUYdU', 'get_ServiceLocator_NoFUYdUService', true],
            'App\\Controller\\RendezVousController::add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\RendezVousController::getEvents' => ['privates', '.service_locator.1a_xG0_', 'get_ServiceLocator_1aXG0Service', true],
            'App\\Controller\\RendezVousController::search' => ['privates', '.service_locator.lmGj34a', 'get_ServiceLocator_LmGj34aService', true],
            'App\\Controller\\RendezVousController::update' => ['privates', '.service_locator.pLzGHnB', 'get_ServiceLocator_PLzGHnBService', true],
            'App\\Controller\\RendezVousController::updateCalendar' => ['privates', '.service_locator.1a_xG0_', 'get_ServiceLocator_1aXG0Service', true],
            'App\\Controller\\ServicesController::add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ServicesController::delete' => ['privates', '.service_locator.MxwGiXI', 'get_ServiceLocator_MxwGiXIService', true],
            'App\\Controller\\ServicesController::getAllServices' => ['privates', '.service_locator._AgMh5.', 'get_ServiceLocator_AgMh5_Service', true],
            'App\\Controller\\ServicesController::getServiceById' => ['privates', '.service_locator.7d4S73s', 'get_ServiceLocator_7d4S73sService', true],
            'App\\Controller\\ServicesController::index' => ['privates', '.service_locator._AgMh5.', 'get_ServiceLocator_AgMh5_Service', true],
            'App\\Controller\\ServicesController::pourcentagSservices' => ['privates', '.service_locator.LroVcfL', 'get_ServiceLocator_LroVcfLService', true],
            'App\\Controller\\ServicesController::update' => ['privates', '.service_locator.MxwGiXI', 'get_ServiceLocator_MxwGiXIService', true],
            'App\\Controller\\StatisticsController::getAllServices' => ['privates', '.service_locator.HWXpj30', 'get_ServiceLocator_HWXpj30Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RendezVousController:AfficheRendezVous' => ['privates', '.service_locator.kMnENF0', 'get_ServiceLocator_KMnENF0Service', true],
            'App\\Controller\\RendezVousController:Delete' => ['privates', '.service_locator.NoFUYdU', 'get_ServiceLocator_NoFUYdUService', true],
            'App\\Controller\\RendezVousController:add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\RendezVousController:getEvents' => ['privates', '.service_locator.1a_xG0_', 'get_ServiceLocator_1aXG0Service', true],
            'App\\Controller\\RendezVousController:search' => ['privates', '.service_locator.lmGj34a', 'get_ServiceLocator_LmGj34aService', true],
            'App\\Controller\\RendezVousController:update' => ['privates', '.service_locator.pLzGHnB', 'get_ServiceLocator_PLzGHnBService', true],
            'App\\Controller\\RendezVousController:updateCalendar' => ['privates', '.service_locator.1a_xG0_', 'get_ServiceLocator_1aXG0Service', true],
            'App\\Controller\\ServicesController:add' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\ServicesController:delete' => ['privates', '.service_locator.MxwGiXI', 'get_ServiceLocator_MxwGiXIService', true],
            'App\\Controller\\ServicesController:getAllServices' => ['privates', '.service_locator._AgMh5.', 'get_ServiceLocator_AgMh5_Service', true],
            'App\\Controller\\ServicesController:getServiceById' => ['privates', '.service_locator.7d4S73s', 'get_ServiceLocator_7d4S73sService', true],
            'App\\Controller\\ServicesController:index' => ['privates', '.service_locator._AgMh5.', 'get_ServiceLocator_AgMh5_Service', true],
            'App\\Controller\\ServicesController:pourcentagSservices' => ['privates', '.service_locator.LroVcfL', 'get_ServiceLocator_LroVcfLService', true],
            'App\\Controller\\ServicesController:update' => ['privates', '.service_locator.MxwGiXI', 'get_ServiceLocator_MxwGiXIService', true],
            'App\\Controller\\StatisticsController:getAllServices' => ['privates', '.service_locator.HWXpj30', 'get_ServiceLocator_HWXpj30Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RendezVousController::AfficheRendezVous' => '?',
            'App\\Controller\\RendezVousController::Delete' => '?',
            'App\\Controller\\RendezVousController::add' => '?',
            'App\\Controller\\RendezVousController::getEvents' => '?',
            'App\\Controller\\RendezVousController::search' => '?',
            'App\\Controller\\RendezVousController::update' => '?',
            'App\\Controller\\RendezVousController::updateCalendar' => '?',
            'App\\Controller\\ServicesController::add' => '?',
            'App\\Controller\\ServicesController::delete' => '?',
            'App\\Controller\\ServicesController::getAllServices' => '?',
            'App\\Controller\\ServicesController::getServiceById' => '?',
            'App\\Controller\\ServicesController::index' => '?',
            'App\\Controller\\ServicesController::pourcentagSservices' => '?',
            'App\\Controller\\ServicesController::update' => '?',
            'App\\Controller\\StatisticsController::getAllServices' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RendezVousController:AfficheRendezVous' => '?',
            'App\\Controller\\RendezVousController:Delete' => '?',
            'App\\Controller\\RendezVousController:add' => '?',
            'App\\Controller\\RendezVousController:getEvents' => '?',
            'App\\Controller\\RendezVousController:search' => '?',
            'App\\Controller\\RendezVousController:update' => '?',
            'App\\Controller\\RendezVousController:updateCalendar' => '?',
            'App\\Controller\\ServicesController:add' => '?',
            'App\\Controller\\ServicesController:delete' => '?',
            'App\\Controller\\ServicesController:getAllServices' => '?',
            'App\\Controller\\ServicesController:getServiceById' => '?',
            'App\\Controller\\ServicesController:index' => '?',
            'App\\Controller\\ServicesController:pourcentagSservices' => '?',
            'App\\Controller\\ServicesController:update' => '?',
            'App\\Controller\\StatisticsController:getAllServices' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
