<?php

namespace ContainerEO8BScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HWXpj30Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HWXpj30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HWXpj30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conn' => ['services', 'doctrine.dbal.default_connection', 'getDoctrine_Dbal_DefaultConnectionService', false],
            'paginator' => ['privates', '.errored.mZjX1DT', NULL, 'Cannot determine controller argument for "App\\Controller\\StatisticsController::getAllServices()": the $paginator argument is type-hinted with the non-existent class or interface: "App\\Controller\\PaginatorInterface". Did you forget to add a use statement?'],
            'repository' => ['privates', '.errored..QTMl8G', NULL, 'Cannot determine controller argument for "App\\Controller\\StatisticsController::getAllServices()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ServicesRepository". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.nUIBIN2', NULL, 'Cannot determine controller argument for "App\\Controller\\StatisticsController::getAllServices()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'conn' => '?',
            'paginator' => '?',
            'repository' => '?',
            'request' => '?',
        ]);
    }
}
