<?php

namespace ContainerEO8BScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_MZjX1DTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.mZjX1DT' shared service.
     *
     * @return \App\Controller\PaginatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\StatisticsController::getAllServices()": the $paginator argument is type-hinted with the non-existent class or interface: "App\\Controller\\PaginatorInterface". Did you forget to add a use statement?');
    }
}
