<?php

namespace ContainerEO8BScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__QTMl8GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..QTMl8G' shared service.
     *
     * @return \App\Controller\ServicesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\StatisticsController::getAllServices()": the $repository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ServicesRepository". Did you forget to add a use statement?');
    }
}
