<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Services extends \App\Entity\Services implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null],
        "\0".parent::class."\0".'created' => [parent::class, 'created', null],
        "\0".parent::class."\0".'dispoDomicile' => [parent::class, 'dispoDomicile', null],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'prix' => [parent::class, 'prix', null],
        "\0".parent::class."\0".'rendezVouss' => [parent::class, 'rendezVouss', null],
        "\0".parent::class."\0".'updated' => [parent::class, 'updated', null],
        'categorie' => [parent::class, 'categorie', null],
        'content' => [parent::class, 'content', null],
        'created' => [parent::class, 'created', null],
        'dispoDomicile' => [parent::class, 'dispoDomicile', null],
        'duree' => [parent::class, 'duree', null],
        'id' => [parent::class, 'id', null],
        'nom' => [parent::class, 'nom', null],
        'prix' => [parent::class, 'prix', null],
        'rendezVouss' => [parent::class, 'rendezVouss', null],
        'updated' => [parent::class, 'updated', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
