<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlGExgF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlGExgF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlGExgF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlGExgF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlGExgF\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlGExgF',
    'container.build_id' => 'f2f825fe',
    'container.build_time' => 1740964900,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlGExgF');
