<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrte2tW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrte2tW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrte2tW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrte2tW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXrte2tW\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xrte2tW',
    'container.build_id' => 'c39e15ac',
    'container.build_time' => 1741053356,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrte2tW');
