<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVx88AjP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVx88AjP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVx88AjP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVx88AjP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVx88AjP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vx88AjP',
    'container.build_id' => 'fb185d4d',
    'container.build_time' => 1741058974,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVx88AjP');
